title: Aaron Roman - Reflexiones
email: aaron.roman@danelfin.com
description: >-
    Co-Founder | Head of Data Engineering & AI at Danelfin | Embracing AI paradigms for agile, data-centric solutions and transformative insights.
baseurl: ""
url: "https://aaronroman.github.io"
twitter_username: aaronroman
github_username: aaronroman
linkedin_username: aaronroman

markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - blog.md

show_excerpts: true